import { randomUUID } from "node:crypto";
import express,{Router,type Request,type Response} from "express";
import { getSupabase } from "../../config/database.js";
import { authenticate } from "../../middleware/auth.js";
import { requirePermission } from "../../middleware/rbac.js";
type Row=Record<string,any>; const router=Router(); router.use(authenticate); router.use(requirePermission("students.self.manage"));
const clean=(v:unknown,n=2000)=>{const s=String(v??"").trim();return s?s.slice(0,n):null};
async function own(req:Request){const q=await getSupabase().from("students").select("*").eq("user_id",req.user!.id).maybeSingle();if(q.error)throw q.error;if(!q.data)throw new Error("Student identity is not linked.");return q.data as Row}
function run(fn:(r:Request)=>Promise<unknown>){return async(req:Request,res:Response)=>{try{res.json({success:true,data:await fn(req)})}catch(e){res.status(400).json({success:false,message:e instanceof Error?e.message:"Student service failed."})}}}
async function enrolled(studentId:string,offeringId:string){const q=await getSupabase().from("course_registrations").select("id").eq("student_id",studentId).eq("course_offering_id",offeringId).in("registration_status",["APPROVED","REGISTERED"]).limit(1);if(q.error||!q.data?.length)throw new Error("This assessment does not belong to a registered course.")}

router.get("/overview",run(async req=>{const db=getSupabase(),s=await own(req);const member=await db.from("library_members").select("*").eq("student_id",s.id).maybeSingle();if(member.error)throw member.error;const [items,reservations,preferences,scholarships,refunds,logs,grad,hostel,calendar]=await Promise.all([
 db.from("library_items").select("id,accession_number,title,author,item_type,available_copies,location,item_status").eq("item_status","AVAILABLE").order("title").limit(300),
 member.data?db.from("library_reservations").select("*").eq("library_member_id",member.data.id).order("created_at",{ascending:false}):Promise.resolve({data:[],error:null}),
 db.from("user_preferences").select("*").eq("user_id",req.user!.id).maybeSingle(), db.from("scholarship_applications").select("*").eq("student_id",s.id).order("created_at",{ascending:false}),
 db.from("refunds").select("*").eq("student_id",s.id).order("created_at",{ascending:false}), db.from("placement_logbook_entries").select("*").eq("student_id",s.id).order("entry_date",{ascending:false}),
 db.from("graduation_applications").select("*").eq("student_id",s.id).order("created_at",{ascending:false}), db.from("hostel_service_requests").select("*").eq("student_id",s.id).order("created_at",{ascending:false}),
 db.from("academic_calendar_events").select("*").in("audience",["ALL","STUDENTS"]).eq("status","PUBLISHED").order("start_at")]);
 for(const x of [items,reservations,preferences,scholarships,refunds,logs,grad,hostel,calendar])if(x.error)throw x.error;
 return{library_member:member.data,library_items:items.data??[],library_reservations:reservations.data??[],preferences:preferences.data,scholarship_applications:scholarships.data??[],refunds:refunds.data??[],logbook:logs.data??[],graduation_applications:grad.data??[],hostel_requests:hostel.data??[],calendar:calendar.data??[]}}));

router.post("/library/reservations",run(async req=>{const db=getSupabase(),s=await own(req),itemId=clean(req.body?.libraryItemId,80);if(!itemId)throw new Error("Library item is required.");const m=await db.from("library_members").select("*").eq("student_id",s.id).eq("membership_status","ACTIVE").maybeSingle();if(m.error||!m.data)throw new Error("Active library membership is required.");const item=await db.from("library_items").select("*").eq("id",itemId).maybeSingle();if(item.error||!item.data||item.data.item_status!=="AVAILABLE")throw new Error("Library item is unavailable.");const exists=await db.from("library_reservations").select("id").eq("library_member_id",m.data.id).eq("library_item_id",itemId).eq("reservation_status","ACTIVE").maybeSingle();if(exists.data)throw new Error("You already have an active reservation for this item.");const q=await db.from("library_reservations").insert({library_member_id:m.data.id,library_item_id:itemId,reservation_status:"ACTIVE",expiry_date:new Date(Date.now()+7*86400000).toISOString().slice(0,10),notes:clean(req.body?.notes)}).select().single();if(q.error)throw q.error;return q.data}));
router.patch("/notifications/:id/read",run(async req=>{const db=getSupabase(),s=await own(req);const q=await db.from("notifications").update({status:"READ",read_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",req.params.id).or(`recipient_student_id.eq.${s.id},recipient_user_id.eq.${req.user!.id}`).select().maybeSingle();if(q.error)throw q.error;if(!q.data)throw new Error("Notification was not found.");return q.data}));
router.put("/preferences",run(async req=>{const allowed=["emailNotifications","smsNotifications","pushNotifications","inAppNotifications"] as const;const p:Row={user_id:req.user!.id,updated_at:new Date().toISOString()};const map:Row={emailNotifications:"email_notifications",smsNotifications:"sms_notifications",pushNotifications:"push_notifications",inAppNotifications:"in_app_notifications"};for(const k of allowed)if(typeof req.body?.[k]==="boolean")p[map[k]]=req.body[k];const q=await getSupabase().from("user_preferences").upsert(p,{onConflict:"user_id"}).select().single();if(q.error)throw q.error;return q.data}));
router.post("/scholarships",run(async req=>{const db=getSupabase(),s=await own(req),name=clean(req.body?.scholarshipName,200),reason=clean(req.body?.reason);if(!name||!reason)throw new Error("Scholarship name and reason are required.");const q=await db.from("scholarship_applications").insert({student_id:s.id,application_number:`SCH-${Date.now()}-${randomUUID().slice(0,6).toUpperCase()}`,scholarship_name:name,sponsor_name:clean(req.body?.sponsorName,200),requested_amount:req.body?.requestedAmount||null,academic_year:clean(req.body?.academicYear,20),reason,status:"SUBMITTED"}).select().single();if(q.error)throw q.error;return q.data}));
router.post("/refunds",run(async req=>{const db=getSupabase(),s=await own(req),paymentId=clean(req.body?.paymentId,80),amount=Number(req.body?.amount),reason=clean(req.body?.reason);if(!paymentId||!(amount>0)||!reason)throw new Error("Payment, positive amount and reason are required.");const p=await db.from("payments").select("*").eq("id",paymentId).eq("student_id",s.id).maybeSingle();if(p.error||!p.data)throw new Error("Payment does not belong to this student.");if(p.data.status!=="CONFIRMED")throw new Error("Only a confirmed payment can be refunded.");const prior=await db.from("refunds").select("amount").eq("payment_id",paymentId).in("status",["REQUESTED","APPROVED","PROCESSING","PAID"]);if(prior.error)throw prior.error;const already=(prior.data??[]).reduce((sum:number,row:Row)=>sum+Number(row.amount||0),0);if(already+amount>Number(p.data.amount||0))throw new Error("Requested refunds would exceed the confirmed payment amount.");const q=await db.from("refunds").insert({payment_id:paymentId,student_id:s.id,refund_number:`REF-${Date.now()}-${randomUUID().slice(0,6).toUpperCase()}`,amount,reason,status:"REQUESTED",requested_by:req.user!.id}).select().single();if(q.error)throw q.error;return q.data}));
router.post("/logbook",run(async req=>{const db=getSupabase(),s=await own(req),clinical=clean(req.body?.clinicalPlacementId,80),field=clean(req.body?.fieldPracticalId,80);if((clinical?1:0)+(field?1:0)!==1)throw new Error("Choose exactly one clinical placement or field practical.");const table=clinical?"clinical_placements":"field_practicals",id=clinical||field;const owner=await db.from(table).select("id,status").eq("id",id!).eq("student_id",s.id).maybeSingle();if(owner.error||!owner.data)throw new Error("Placement does not belong to this student.");const q=await db.from("placement_logbook_entries").insert({student_id:s.id,clinical_placement_id:clinical,field_practical_id:field,entry_date:clean(req.body?.entryDate,10),activity_title:clean(req.body?.activityTitle,200),activity_description:clean(req.body?.activityDescription),hours_completed:Number(req.body?.hoursCompleted||0),competencies:clean(req.body?.competencies),student_status:"SUBMITTED"}).select().single();if(q.error)throw q.error;return q.data}));

async function store(req:Request,prefix:string){const body=req.body as Buffer,name=clean(req.headers["x-file-name"],255)?.replace(/[^a-zA-Z0-9._-]/g,"_"),mime=clean(req.headers["x-mime-type"],100)||"application/octet-stream";if(!Buffer.isBuffer(body)||!body.length||!name)throw new Error("File is required.");if(!["application/pdf","image/jpeg","image/png","image/webp"].includes(mime))throw new Error("Only PDF/JPG/PNG/WEBP files are allowed.");const path=`${prefix}/${Date.now()}-${randomUUID().slice(0,8)}-${name}`;const q=await getSupabase().storage.from("idmc-private-documents").upload(path,body,{contentType:mime});if(q.error)throw q.error;return path}
router.post("/assessments/upload",express.raw({type:"application/octet-stream",limit:"6mb"}),run(async req=>{const db=getSupabase(),s=await own(req),id=clean(req.headers["x-assessment-id"],80);if(!id)throw new Error("Assessment is required.");const a=await db.from("assessments").select("*").eq("id",id).maybeSingle();if(a.error||!a.data)throw new Error("Assessment was not found.");await enrolled(s.id,a.data.course_offering_id);if(a.data.status!=="OPEN")throw new Error("Assessment is not open for submission.");const path=await store(req,`students/${s.id}/assessments`),late=a.data.due_date&&Date.now()>Date.parse(a.data.due_date);const q=await db.from("assessment_submissions").upsert({assessment_id:id,student_id:s.id,submitted_at:new Date().toISOString(),submission_status:late?"LATE":"SUBMITTED",submission_reference:path,remarks:clean(req.headers["x-remarks"],500),updated_at:new Date().toISOString()},{onConflict:"assessment_id,student_id"}).select().single();if(q.error)throw q.error;return q.data}));
router.post("/field-reports/upload",express.raw({type:"application/octet-stream",limit:"6mb"}),run(async req=>{const db=getSupabase(),s=await own(req),id=clean(req.headers["x-field-practical-id"],80),title=clean(req.headers["x-report-title"],200);if(!id||!title)throw new Error("Field practical and report title are required.");const f=await db.from("field_practicals").select("id").eq("id",id).eq("student_id",s.id).maybeSingle();if(f.error||!f.data)throw new Error("Field practical does not belong to this student.");const path=await store(req,`students/${s.id}/field-reports`);const q=await db.from("field_practical_reports").insert({field_practical_id:id,report_type:clean(req.headers["x-report-type"],40)||"FINAL",title,file_url:path,submitted_at:new Date().toISOString(),status:"SUBMITTED"}).select().single();if(q.error)throw q.error;return q.data}));
export default router;
