import { Router } from "express";
import { authenticate } from "../../middleware/auth.js";
import { requirePermission } from "../../middleware/rbac.js";
import { getSupabase } from "../../config/database.js";
import { registerCrudResource } from "../../utils/resourceCrud.js";
const router=Router(); router.use(authenticate);
const VIEW="examinations.view", MANAGE="examinations.manage", MARKS="examinations.marks.manage", CORRECT="examinations.corrections.manage";
const paperTypes = new Set(["FINAL","SUPPLEMENTARY","SPECIAL","RESIT","MAKEUP"]);
router.post("/papers", requirePermission(MANAGE), async (req,res,next)=>{try{
  const db=getSupabase(), periodId=String(req.body?.examinationPeriodId??"").trim(), offeringId=String(req.body?.courseOfferingId??"").trim();
  if(!periodId||!offeringId)return res.status(400).json({success:false,message:"Examination Period and Course Offering are required."});
  const [period,offering]=await Promise.all([
    db.from("examination_periods").select("id,examination_type,status").eq("id",periodId).maybeSingle(),
    db.from("course_offerings").select("id,offering_code,course_id,status,courses(course_code,course_name)").eq("id",offeringId).maybeSingle()
  ]);
  if(period.error)throw period.error;if(offering.error)throw offering.error;
  if(!period.data)return res.status(404).json({success:false,message:"Selected Examination Period no longer exists."});
  if(!offering.data)return res.status(404).json({success:false,message:"Selected Course Offering no longer exists."});
  if(["PUBLISHED","COMPLETED","LOCKED","CANCELLED"].includes(period.data.status))return res.status(409).json({success:false,message:`Papers cannot be added while the period is ${period.data.status}.`});
  const requested=String(req.body?.examinationType??period.data.examination_type??"FINAL").toUpperCase();
  const examinationType=requested==="END_OF_SEMESTER"||requested==="MID_SEMESTER"?"FINAL":requested;
  if(!paperTypes.has(examinationType))return res.status(400).json({success:false,message:"Paper type must be FINAL, SUPPLEMENTARY, SPECIAL, RESIT or MAKEUP."});
  const course:any=Array.isArray(offering.data.courses)?offering.data.courses[0]:offering.data.courses;
  const paperCode=String(req.body?.paperCode??`${course?.course_code??offering.data.offering_code}-${examinationType}`).trim().slice(0,80);
  const maximumMarks=Number(req.body?.maximumMarks??100),durationMinutes=Number(req.body?.durationMinutes??180);
  if(!paperCode)return res.status(400).json({success:false,message:"Paper Code is required."});
  if(!(maximumMarks>0)||!(durationMinutes>0))return res.status(400).json({success:false,message:"Maximum Marks and Duration must be greater than zero."});
  const saved=await db.from("examination_papers").insert({examination_period_id:periodId,course_offering_id:offeringId,paper_code:paperCode,paper_title:String(req.body?.paperTitle??course?.course_name??paperCode).trim().slice(0,200),examination_type:examinationType,maximum_marks:maximumMarks,duration_minutes:durationMinutes,instructions:req.body?.instructions?String(req.body.instructions).trim():null,status:"DRAFT",created_by:req.user!.id,updated_by:req.user!.id}).select("*").single();
  if(saved.error){if(saved.error.code==="23505")return res.status(409).json({success:false,message:"This Paper Code already exists in the selected Examination Period."});throw saved.error;}
  return res.status(201).json({success:true,data:saved.data,message:"Examination paper created successfully."});
}catch(error){next(error);}});
router.post("/periods/:id/publish", requirePermission(MANAGE), async (req, res, next) => { try { const db=getSupabase(), id=String(req.params.id), period=await db.from("examination_periods").select("*").eq("id",id).maybeSingle(); if(period.error)throw period.error; if(!period.data)return res.status(404).json({success:false,message:"Examination period not found."}); if(!["DRAFT","PLANNING","APPROVED","PUBLISHED"].includes(period.data.status))return res.status(409).json({success:false,message:`Cannot publish a period in ${period.data.status} status.`}); const papers=await db.from("examination_papers").select("id").eq("examination_period_id",id); if(papers.error)throw papers.error; if(!(papers.data||[]).length)return res.status(409).json({success:false,message:"Add at least one examination paper before publishing."}); const paperIds=(papers.data||[]).map((p:any)=>p.id), scheduled=await db.from("examination_sessions").select("id").in("examination_paper_id",paperIds).limit(1); if(scheduled.error)throw scheduled.error; if(!(scheduled.data||[]).length)return res.status(409).json({success:false,message:"Schedule at least one examination session before publishing."}); const now=new Date().toISOString(), updated=await db.from("examination_periods").update({status:"PUBLISHED",published_by:req.user!.id,published_at:now,updated_by:req.user!.id,updated_at:now}).eq("id",id).select("*").single(); if(updated.error)throw updated.error; res.json({success:true,data:updated.data,message:"Examination timetable published to eligible students."}); }catch(error){next(error);} });
registerCrudResource(router,{moduleCode:"EXAMINATIONS",entityType:"examination_periods",table:"examination_periods",permissionView:VIEW,permissionManage:MANAGE,searchFields:["period_code","period_name","examination_type","status"],filterFields:["academic_year_id","semester_id","examination_type","status"],defaultOrderField:"start_date",fields:{academicYearId:"academic_year_id",semesterId:"semester_id",periodCode:"period_code",periodName:"period_name",examinationType:"examination_type",startDate:"start_date",endDate:"end_date",status:"status",approvedBy:"approved_by",approvedAt:"approved_at",publishedBy:"published_by",publishedAt:"published_at",lockedBy:"locked_by",lockedAt:"locked_at",notes:"notes",createdBy:"created_by",updatedBy:"updated_by"}},"/periods");
registerCrudResource(router,{moduleCode:"EXAMINATIONS",entityType:"examination_papers",table:"examination_papers",permissionView:VIEW,permissionManage:MANAGE,searchFields:["paper_code","paper_title","examination_type","status"],filterFields:["examination_period_id","course_offering_id","examination_type","status"],defaultOrderField:"created_at",fields:{examinationPeriodId:"examination_period_id",courseOfferingId:"course_offering_id",paperCode:"paper_code",paperTitle:"paper_title",examinationType:"examination_type",maximumMarks:"maximum_marks",durationMinutes:"duration_minutes",instructions:"instructions",status:"status",createdBy:"created_by",updatedBy:"updated_by",approvedBy:"approved_by",approvedAt:"approved_at",lockedBy:"locked_by",lockedAt:"locked_at"}},"/papers");
registerCrudResource(router,{moduleCode:"EXAMINATIONS",entityType:"examination_sessions",table:"examination_sessions",permissionView:VIEW,permissionManage:MANAGE,searchFields:["session_code","status"],filterFields:["examination_paper_id","campus_id","room_id","examination_date","status"],defaultOrderField:"examination_date",fields:{examinationPaperId:"examination_paper_id",campusId:"campus_id",roomId:"room_id",examinationDate:"examination_date",startTime:"start_time",endTime:"end_time",sessionCode:"session_code",capacity:"capacity",status:"status",createdBy:"created_by",updatedBy:"updated_by",approvedBy:"approved_by",approvedAt:"approved_at",lockedBy:"locked_by",lockedAt:"locked_at"}},"/sessions");
registerCrudResource(router,{moduleCode:"EXAMINATIONS",entityType:"examination_candidates",table:"examination_candidates",permissionView:VIEW,permissionManage:MANAGE,searchFields:["candidate_number","eligibility_status","attendance_status","candidate_status"],filterFields:["examination_paper_id","student_id","course_registration_id","eligibility_status","candidate_status"],defaultOrderField:"created_at",fields:{examinationPaperId:"examination_paper_id",studentId:"student_id",courseRegistrationId:"course_registration_id",candidateNumber:"candidate_number",eligibilityStatus:"eligibility_status",eligibilityReason:"eligibility_reason",attendanceStatus:"attendance_status",candidateStatus:"candidate_status"}},"/candidates");
registerCrudResource(router,{moduleCode:"EXAMINATIONS",entityType:"examination_candidate_sessions",table:"examination_candidate_sessions",permissionView:VIEW,permissionManage:MANAGE,searchFields:["seat_number","assignment_status","notes"],filterFields:["examination_session_id","examination_candidate_id","assignment_status"],defaultOrderField:"created_at",fields:{examinationSessionId:"examination_session_id",examinationCandidateId:"examination_candidate_id",seatNumber:"seat_number",assignmentStatus:"assignment_status",assignedBy:"assigned_by",assignedAt:"assigned_at",notes:"notes"}},"/candidate-sessions");
registerCrudResource(router,{moduleCode:"EXAMINATIONS",entityType:"examination_attendance",table:"examination_attendance",permissionView:VIEW,permissionManage:MANAGE,searchFields:["attendance_status","seat_number","remarks"],filterFields:["examination_session_id","examination_candidate_id","attendance_status"],defaultOrderField:"marked_at",fields:{examinationSessionId:"examination_session_id",examinationCandidateId:"examination_candidate_id",attendanceStatus:"attendance_status",checkInTime:"check_in_time",seatNumber:"seat_number",identityVerified:"identity_verified",remarks:"remarks",markedBy:"marked_by",markedAt:"marked_at"}},"/attendance");
registerCrudResource(router,{moduleCode:"EXAMINATIONS",entityType:"examination_invigilators",table:"examination_invigilators",permissionView:VIEW,permissionManage:MANAGE,searchFields:["assignment_role","status","notes"],filterFields:["examination_session_id","user_id","assignment_role","status"],defaultOrderField:"created_at",fields:{examinationSessionId:"examination_session_id",userId:"user_id",assignmentRole:"assignment_role",status:"status",assignedBy:"assigned_by",assignedAt:"assigned_at",confirmedAt:"confirmed_at",notes:"notes"}},"/invigilators");
registerCrudResource(router,{moduleCode:"EXAMINATIONS",entityType:"examination_marks",table:"examination_marks",permissionView:VIEW,permissionManage:MARKS,searchFields:["grade","status","remarks"],filterFields:["examination_paper_id","examination_candidate_id","student_id","course_registration_id","status"],defaultOrderField:"created_at",fields:{examinationPaperId:"examination_paper_id",examinationCandidateId:"examination_candidate_id",studentId:"student_id",courseRegistrationId:"course_registration_id",marks:"marks",percentage:"percentage",grade:"grade",remarks:"remarks",status:"status",enteredBy:"entered_by",enteredAt:"entered_at",submittedBy:"submitted_by",submittedAt:"submitted_at",approvedBy:"approved_by",approvedAt:"approved_at",lockedBy:"locked_by",lockedAt:"locked_at"}},"/marks");
registerCrudResource(router,{moduleCode:"EXAMINATIONS",entityType:"examination_mark_corrections",table:"examination_mark_corrections",permissionView:VIEW,permissionManage:CORRECT,searchFields:["reason","status","review_comment"],filterFields:["examination_mark_id","requested_by","status"],defaultOrderField:"requested_at",fields:{examinationMarkId:"examination_mark_id",requestedBy:"requested_by",requestedAt:"requested_at",oldMarks:"old_marks",newMarks:"new_marks",oldGrade:"old_grade",newGrade:"new_grade",reason:"reason",evidenceFileId:"evidence_file_id",status:"status",reviewedBy:"reviewed_by",reviewedAt:"reviewed_at",reviewComment:"review_comment"}},"/mark-corrections");
export default router;
