import { Router,type Request,type Response } from "express";
import { getSupabase } from "../../config/database.js";
import { authenticate } from "../../middleware/auth.js";
type Row=Record<string,any>; const router=Router();router.use(authenticate);
async function context(req:Request){const db=getSupabase();const roles=await db.from("user_roles").select("status,expires_at,roles!inner(role_code,status)").eq("user_id",req.user!.id).eq("status","ACTIVE");if(roles.error)throw roles.error;const codes=(roles.data??[]).filter((x:any)=>x.roles?.status==="ACTIVE"&&(!x.expires_at||Date.parse(x.expires_at)>Date.now())).map((x:any)=>String(x.roles.role_code));const staff=await db.from("staff").select("*").eq("user_id",req.user!.id).maybeSingle();if(staff.error)throw staff.error;if(!staff.data&&!codes.some(x=>["ADMIN","SUPER_ADMIN","SYSTEM_ADMIN"].includes(x)))throw new Error("Staff profile is not linked to this account.");return{codes,staff:staff.data}}
const groups:Record<string,string[]>={hr:["HR_OFFICER"],admissions:["ADMISSIONS_OFFICER"],examinations:["EXAMINATION_OFFICER","EXAMINATIONS_OFFICER","EXAM_OFFICER"],library:["LIBRARIAN"],operations:["PROCUREMENT_OFFICER","STORE_OFFICER","OPERATIONS_OFFICER"],academic:["HOD","DEPUTY_HOD","ACADEMIC_OFFICER","REGISTRAR"],communications:["COMMUNICATIONS_OFFICER","HELPDESK_OFFICER","DOCUMENTS_OFFICER"],management:["ADMIN","SUPER_ADMIN","SYSTEM_ADMIN","REPORTS_OFFICER","AUDITOR"]};
function allowed(codes:string[],group:string){return codes.some(x=>(groups[group]??[]).includes(x)||["ADMIN","SUPER_ADMIN"].includes(x))}
async function rows(table:string,order="created_at",limit=80,filter?:[string,unknown]){let q:any=getSupabase().from(table).select("*").order(order,{ascending:false}).limit(limit);if(filter&&filter[1])q=q.eq(filter[0],filter[1]);const r=await q;return r.error?{rows:[],warning:`${table}: ${r.error.message}`}:{rows:r.data??[],warning:null}}
router.get("/overview",async(req:Request,res:Response)=>{try{const c=await context(req),sections:Row[]=[],warnings:string[]=[];async function add(code:string,title:string,link:string,sets:any[]){const queues=[];for(const [table,label,order,filter] of sets){const r=await rows(table,order||"created_at",80,filter);if(r.warning)warnings.push(r.warning);queues.push({table,label,rows:r.rows})}sections.push({code,title,link,queues})}
 if(allowed(c.codes,"hr"))await add("hr","Human Resources","hr.html",[["staff_leave_requests","Pending Leave","created_at"],["staff","Staff Register","created_at",c.staff?.institution_id?["institution_id",c.staff.institution_id]:undefined],["staff_attendance","Recent Attendance","attendance_date"],["staff_payroll_entries","Payroll Queue","created_at"]]);
 if(allowed(c.codes,"admissions"))await add("admissions","Admissions","admissions.html",[["applications","Application Queue","created_at"],["admission_decisions","Decisions","decision_date"],["admission_offers","Offers","offer_date"]]);
 if(allowed(c.codes,"examinations"))await add("examinations","Examinations","examinations.html",[["examination_sessions","Exam Sessions","examination_date"],["examination_candidates","Candidate Eligibility","created_at"],["examination_marks","Marks Queue","created_at"],["examination_mark_corrections","Corrections","requested_at"]]);
 if(allowed(c.codes,"library"))await add("library","Library Circulation","library.html",[["library_loans","Loans","loan_date"],["library_reservations","Reservations","created_at"],["library_fines","Fines","created_at"],["library_items","Catalogue","created_at"]]);
 if(allowed(c.codes,"operations"))await add("operations","Procurement & Stores","operations.html",[["procurement_requests","Requisitions","request_date"],["purchase_orders","Purchase Orders","order_date"],["inventory_items","Inventory","created_at"],["inventory_transactions","Stock Movements","transaction_date"]]);
 if(allowed(c.codes,"academic"))await add("academic","Academic Department","programmes.html",[["course_offerings","Course Offerings","created_at"],["lecturer_assignments","Teaching Load","assigned_at"],["student_registrations","Registrations","created_at"],["course_results","Results Queue","created_at"]]);
 if(allowed(c.codes,"communications"))await add("communications","Communications & Helpdesk","communications.html",[["helpdesk_tickets","Helpdesk Queue","created_at"],["announcements","Announcements","created_at"],["documents","Document Registry","created_at"],["notification_queue","Notification Queue","created_at"]]);
 if(allowed(c.codes,"management"))await add("management","Management Oversight","reports.html",[["students","Students","created_at"],["staff","Staff","created_at"],["invoices","Invoices","created_at"],["payments","Payments","created_at"],["audit_logs","Audit Activity","created_at"]]);
 if(!sections.length)throw new Error("No operational workspace is assigned to your active role.");res.json({success:true,data:{user:req.user,staff:c.staff,roles:c.codes,sections,warnings}})}catch(e){res.status(403).json({success:false,message:e instanceof Error?e.message:"Unable to load staff operations."})}});
export default router;
