import { Router } from "express";
import { authenticate } from "../../middleware/auth.js";
import { registerCrudResource } from "../../utils/resourceCrud.js";

const router = Router(); router.use(authenticate);
const VIEW="assessment.view"; const MANAGE="assessment.manage"; const CORRECT="assessment.corrections.manage";
registerCrudResource(router,{moduleCode:"ASSESSMENT",entityType:"assessments",table:"assessments",permissionView:VIEW,permissionManage:MANAGE,searchFields:["assessment_code","assessment_name","assessment_type","status"],filterFields:["course_offering_id","assessment_type","status"],defaultOrderField:"due_date",fields:{courseOfferingId:"course_offering_id",assessmentCode:"assessment_code",assessmentName:"assessment_name",assessmentType:"assessment_type",assessmentNumber:"assessment_number",maximumMarks:"maximum_marks",weightPercentage:"weight_percentage",dueDate:"due_date",dueTime:"due_time",status:"status",instructions:"instructions",createdBy:"created_by",updatedBy:"updated_by",approvedBy:"approved_by",approvedAt:"approved_at",lockedBy:"locked_by",lockedAt:"locked_at"}},"/assessments");
registerCrudResource(router,{moduleCode:"ASSESSMENT",entityType:"assessment_submissions",table:"assessment_submissions",permissionView:VIEW,permissionManage:MANAGE,searchFields:["submission_status","submission_reference","remarks"],filterFields:["assessment_id","student_id","submission_status"],defaultOrderField:"submitted_at",fields:{assessmentId:"assessment_id",studentId:"student_id",submittedAt:"submitted_at",submissionStatus:"submission_status",fileId:"file_id",submissionReference:"submission_reference",remarks:"remarks"}},"/submissions");
registerCrudResource(router,{moduleCode:"ASSESSMENT",entityType:"assessment_marks",table:"assessment_marks",permissionView:VIEW,permissionManage:MANAGE,searchFields:["grade","status","remarks"],filterFields:["assessment_id","student_id","course_registration_id","status"],defaultOrderField:"created_at",fields:{assessmentId:"assessment_id",studentId:"student_id",courseRegistrationId:"course_registration_id",marks:"marks",percentage:"percentage",grade:"grade",remarks:"remarks",status:"status",enteredBy:"entered_by",enteredAt:"entered_at",submittedBy:"submitted_by",submittedAt:"submitted_at",approvedBy:"approved_by",approvedAt:"approved_at"}},"/marks");
registerCrudResource(router,{moduleCode:"ASSESSMENT",entityType:"assessment_mark_corrections",table:"assessment_mark_corrections",permissionView:VIEW,permissionManage:CORRECT,searchFields:["reason","status","review_comment"],filterFields:["assessment_mark_id","requested_by","status"],defaultOrderField:"requested_at",fields:{assessmentMarkId:"assessment_mark_id",requestedBy:"requested_by",requestedAt:"requested_at",oldMarks:"old_marks",newMarks:"new_marks",oldGrade:"old_grade",newGrade:"new_grade",reason:"reason",evidenceFileId:"evidence_file_id",status:"status",reviewedBy:"reviewed_by",reviewedAt:"reviewed_at",reviewComment:"review_comment"}},"/mark-corrections");
export default router;
