import { Router } from "express";
import { authenticate } from "../../middleware/auth.js";
import { registerCrudResource } from "../../utils/resourceCrud.js";

const router = Router();
router.use(authenticate);

registerCrudResource(router, { moduleCode:"CLINICAL", entityType:"placement_sites", table:"placement_sites", permissionView:"clinical.view", permissionManage:"clinical.manage", searchFields:["site_code","site_name","site_type","contact_person","region","district"], filterFields:["institution_id","site_type","status"], fields:{ institutionId:"institution_id", siteCode:"site_code", siteName:"site_name", siteType:"site_type", registrationNumber:"registration_number", contactPerson:"contact_person", phone:"phone", email:"email", physicalAddress:"physical_address", region:"region", district:"district", capacity:"capacity", agreementStartDate:"agreement_start_date", agreementEndDate:"agreement_end_date", status:"status", notes:"notes" } }, "/clinical/sites");
registerCrudResource(router, { moduleCode:"CLINICAL", entityType:"clinical_placements", table:"clinical_placements", permissionView:"clinical.view", permissionManage:"clinical.manage", searchFields:["placement_number","department_unit","status","final_grade"], filterFields:["student_id","placement_site_id","academic_year_id","semester_id","course_id","supervisor_staff_id","status"], defaultOrderField:"start_date", fields:{ studentId:"student_id", placementSiteId:"placement_site_id", academicYearId:"academic_year_id", semesterId:"semester_id", courseId:"course_id", supervisorStaffId:"supervisor_staff_id", placementNumber:"placement_number", departmentUnit:"department_unit", startDate:"start_date", endDate:"end_date", requiredHours:"required_hours", completedHours:"completed_hours", status:"status", finalScore:"final_score", finalGrade:"final_grade", remarks:"remarks", createdBy:"created_by" } }, "/clinical/placements");
registerCrudResource(router, { moduleCode:"CLINICAL", entityType:"clinical_assessments", table:"clinical_assessments", permissionView:"clinical.view", permissionManage:"clinical.manage", searchFields:["assessment_type","assessor_name","competency_rating","feedback","status"], filterFields:["clinical_placement_id","assessor_staff_id","status"], defaultOrderField:"assessment_date", fields:{ clinicalPlacementId:"clinical_placement_id", assessmentType:"assessment_type", assessmentDate:"assessment_date", assessorName:"assessor_name", assessorStaffId:"assessor_staff_id", score:"score", competencyRating:"competency_rating", feedback:"feedback", evidenceUrl:"evidence_url", status:"status" } }, "/clinical/assessments");

registerCrudResource(router, { moduleCode:"FIELD_PRACTICAL", entityType:"field_organizations", table:"field_organizations", permissionView:"field_practical.view", permissionManage:"field_practical.manage", searchFields:["organization_code","organization_name","industry_sector","contact_person","region","district"], filterFields:["institution_id","industry_sector","status"], fields:{ institutionId:"institution_id", organizationCode:"organization_code", organizationName:"organization_name", industrySector:"industry_sector", contactPerson:"contact_person", phone:"phone", email:"email", physicalAddress:"physical_address", region:"region", district:"district", capacity:"capacity", status:"status", notes:"notes" } }, "/field/organizations");
registerCrudResource(router, { moduleCode:"FIELD_PRACTICAL", entityType:"field_practicals", table:"field_practicals", permissionView:"field_practical.view", permissionManage:"field_practical.manage", searchFields:["practical_number","status","final_grade","remarks"], filterFields:["student_id","field_organization_id","academic_year_id","semester_id","course_id","supervisor_staff_id","status"], defaultOrderField:"start_date", fields:{ studentId:"student_id", fieldOrganizationId:"field_organization_id", academicYearId:"academic_year_id", semesterId:"semester_id", courseId:"course_id", supervisorStaffId:"supervisor_staff_id", practicalNumber:"practical_number", startDate:"start_date", endDate:"end_date", requiredHours:"required_hours", completedHours:"completed_hours", status:"status", supervisorScore:"supervisor_score", academicScore:"academic_score", finalScore:"final_score", finalGrade:"final_grade", remarks:"remarks", createdBy:"created_by" } }, "/field/practicals");
registerCrudResource(router, { moduleCode:"FIELD_PRACTICAL", entityType:"field_practical_reports", table:"field_practical_reports", permissionView:"field_practical.view", permissionManage:"field_practical.manage", searchFields:["report_type","title","feedback","status"], filterFields:["field_practical_id","report_type","status"], defaultOrderField:"created_at", fields:{ fieldPracticalId:"field_practical_id", reportType:"report_type", title:"title", fileUrl:"file_url", submittedAt:"submitted_at", reviewedBy:"reviewed_by", reviewedAt:"reviewed_at", score:"score", feedback:"feedback", status:"status" } }, "/field/reports");

export default router;
